name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Run Day 1
        run: cargo run --verbose
        working-directory: day01

      - name: Run tests Day 1
        run: cargo test --verbose
        working-directory: day01

      - name: Run Day 2
        run: cargo run --verbose
        working-directory: day02

      - name: Run tests Day 2
        run: cargo test --verbose
        working-directory: day02

      - name: Run Day 3
        run: cargo run --verbose
        working-directory: day03

      - name: Run tests Day 3
        run: cargo test --verbose
        working-directory: day03

      - name: Run Day 4
        run: cargo run --verbose
        working-directory: day04

      - name: Run tests Day 4
        run: cargo test --verbose
        working-directory: day04

      - name: Run Day 5
        run: cargo run --verbose
        working-directory: day05

      - name: Run tests Day 5
        run: cargo test --verbose
        working-directory: day05

      - name: Run Day 6
        run: cargo run --verbose
        working-directory: day06

      - name: Run tests Day 6
        run: cargo test --verbose
        working-directory: day06

      - name: Run Day 7
        run: cargo run --verbose
        working-directory: day07

      - name: Run tests Day 7
        run: cargo test --verbose
        working-directory: day07

      - name: Run Day 8
        run: cargo run --verbose
        working-directory: day08

      - name: Run tests Day 8
        run: cargo test --verbose
        working-directory: day08

      - name: Run Day 9
        run: cargo run --verbose
        working-directory: day09

      - name: Run tests Day 9
        run: cargo test --verbose
        working-directory: day09
